#!/bin/bash

# Calculate Diffusion for each run
# Inputs:
#	<directory containing all jobs>
#	<generic name for jobs>
#	<export directory for analysis>
#	<name of directory containing analysis data>
#       <name of directory containing analysis plots>
#	<name of trajectory file>
#	<name of LAMMPS print to screen file>
#	<name of input file>
#	<the significance level for two sided t-test for finding settled data>

diffusion_iterator.py\
	'../data'\
	'job'\
	'../export'\
       	'analysis_data'\
       	'analysis_plots'\
       	'traj.lammpstrj'\
       	'test.out'\
       	'dep.in'\
	'0.05'
