#!/bin/bash

# Calculate mean Tg from gathered Tg values
# Inputs:
#       <path to Tg dataframe>
#	<export directory>

python3 python/calculate_mean_tg.py\
       	'../export/analysis_data/tg_df.txt'\
	'../export/analysis_data'
