#!/bin/bash

# Calculate ICO fraction at Tg hold
# Inputs:
#	<directory containing all jobs>
#	<generic name for jobs>
#	<export directory for analysis>
#	<name of directory containing analysis data>
#       <name of directory containing analysis plots>
#	<name of trajectory file>
#	<name of LAMMPS print to screen file>
#	<name of input file>
#	<edges of interest>
#	<minimum number of faces for corresponding edges>

ico_at_tg_iterator.py\
	'../data'\
	'job'\
	'../export'\
       	'analysis_data'\
       	'analysis_plots'\
       	'traj.lammpstrj'\
       	'test.out'\
       	'dep.in'\
	'5'\
	'10'
