#!/bin/bash

# Calculate APD for each run
# Inputs:
#	<directory containing all jobs>
#	<generic directory containing data files>
#       <name of trajectory file>
#       <name of input file>
#	<export directory for analysis>
#	<name of directory containing analysis data>

python3 python/apd_iterator.py\
	'../data'\
	'100K_Structure_minimization'\
        'finaltraj.lammpstrj'\
        '100k_minimize_template.in'\
	'../export'\
       	'analysis_data'
