#!/bin/bash

# Calculate max cluster variance for each run
# Inputs:
#	<directory containing all jobs>
#	<generic name for jobs>
#	<export directory for analysis>
#	<name of directory containing analysis data>
#       <name of directory containing analysis plots>
#	<name of trajectory file>
#	<name of input file>

variance_iterator.py\
	'../data'\
	'job'\
	'../export'\
       	'analysis_data'\
       	'analysis_plots'\
       	'traj.lammpstrj'\
       	'dep.in'
