#!/usr/bin/python3

from matplotlib import pyplot as pl

import pandas as pd
import numpy as np

import os
import re

dtemp = 50  # The change in temperature [K]
timestep = 0.001  # The timestep [ps]

dataframe = '../analysis_data/meantg.txt'  # The name and path of the dataframe
savefolder = '../analysis_plots/'  # The name of the save folder for the images

if not os.path.exists(savefolder):
    os.makedirs(savefolder)

df = pd.read_csv(dataframe)
group = df.groupby(['System', 'Steps [-]'])

for i in group:

    data = i[1]

    system = i[0][0]
    elements = system.split('-')

    rate = dtemp/(i[0][1]*timestep*1e-12)

    y = data['Mean Tg from E-3kT Curve [K]'].values
    yerr = data['SEM Tg from E-3kT Curve [K]'].values

    x = data['Composition [decimal]']

    x =  [float(re.findall("\d+\.\d+", i)[0]) for i in x]

    fig, ax = pl.subplots()

    ax.errorbar(
                x,
                y,
                yerr,
                marker='.',
                ecolor='r',
                linestyle='none',
                label='Cooling Rate: '+"{:.2E}".format(rate)+' [K/s]'
                )


    ax.set_xlabel('Fraction of '+elements[1]+' in '+elements[0])
    ax.set_ylabel('Tg [K]')

    ax.grid()
    ax.legend(loc='best')

    fig.tight_layout()

    name = i[0][0]+'_'+str(i[0][1])

    fig.savefig(savefolder+'composition_vs_tg_'+name)
