#!/usr/bin/python3

import shutil
import os

destination = '../export'

folders = ['analysis_plots', 'analysis_data']
for item in os.walk('../'):

    path = item[0]
    split = path.split('/')

    if split[-1] not in folders:
        continue

    export_path = path.strip('../')
    export_path = os.path.join(destination, export_path)

    shutil.copytree(path, export_path)
    print('Copying '+path+' folder to '+export_path)

