#!/bin/bash

# Gather APD values from analysis
# Inputs:
#       <analysis data from jobs>
#	<name of file containing APD>
#       <export directory>

gather_apd.py\
       	'../export'\
       	'apd_last.txt'\
       	'../export/analysis_data'
