#!/bin/bash

# Gather Tg values from analysis
# Inputs:
#       <analysis data from jobs>
#	<name of file containing Tg>
#	<name of the file containing cutoff temperature for Tg>
#       <export directory>

gather_tg.py\
       	'../export'\
       	'etg.txt'\
	'etg_temp_cutoff.txt'\
       	'../export/analysis_data'
