#!/bin/bash

# Delete recursively folders and contents matching a list input.
# Inputs:
#       <directory containing all jobs>
#       <generic name of directory to be removed 1>
#       <generic name of directory to be removed 2>
#	...
#       <generic name of directory to be removed n>

python3	python/remove_calculations.py\
	'../data'\
	'analysis_scripts'\
	'analysis_plots'\
	'analysis_data'\
