#!/bin/bash

# Gather the Voronoi Polyhedra (VP) indexes

EXPORT="export"

for d in */ ; do
	iterator_2450k_minimization.py\
		./$d\
		8\
		minimized_traj.lammpstrj\
		log.lammps\
		0.1\
		10\
		./"$EXPORT"
done
