#!/usr/bin/python3

from matplotlib import pyplot as pl

from scipy import stats

import pandas as pd
import numpy as np

import sys
import os

file_path = sys.argv[1]
figure_path = sys.argv[2]

if not os.path.exists(figure_path):
    os.makedirs(figure_path)

df = pd.read_csv(file_path)

df = df.drop(['Tg from Specific Volume Curve [K]'], axis=1)

group = df.groupby(['System', 'Composition [decimal]', 'Steps [-]'])

for item in group:

    system = item[0][0]
    composition = item[0][1]
    steps = item[0][2]

    x = item[1]['Job'].values
    x = [int(i.strip('job')) for i in x]
    y = item[1]['Tg from E-3kT Curve [K]'].values

    mean = np.mean(y)
    stdev = np.std(y, ddof=1)
    sem = stats.sem(y, ddof=1)

    fig, ax = pl.subplots()

    ax.bar(x, y)

    ax.set_xlabel('Jobs')
    ax.set_ylabel('Tg [K]')

    ax.set_xticks(x)

    info = (
            'System: ' +
            system +
            '\n' +
            'Composition: ' +
            composition +
            '\n' +
            'Steps: ' +
            str(steps) +
            '\n' +
            'Mean = ' +
            str(round(mean, 2)) +
            '\n' +
            'STDEV = ' +
            str(round(stdev, 2)) +
            '\n' + 
            'SEM = ' +
            str(round(sem, 2))
            )

    ax.annotate(info, xy=(0.8, 0.75), xycoords='figure fraction')

    fig.subplots_adjust(right=0.75)
    fig.set_size_inches(10, 5)

    name = os.path.join(figure_path, '_'.join(map(str, item[0]))+'_tg')
    print('Saving: '+name)
    fig.savefig(name, format='png')

    pl.close('all')
